server:
  port: 8086
  
  
spring:
  application:
    name: CONFIG-SERVER
    
  profiles:
    active:
    - native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Sachin-ops/microservice-config
          clone-on-start: true
    

    
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
  service-url:
    defaultZone: http://localhost:8761/eureka
      
    
    