spring:
  application:
    name: FINANCE-SECURITY



    main:
    allow-circular-references: true

  datasource:
    url: jdbc:postgresql://localhost:5432/Microservice
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
server:
  port: 8087
  
logging:
  level:
    org.springframework: INFO
    com.your.package: DEBUG
    feign: DEBUG
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
  service-url:
    defaultZone: http://localhost:8761/eureka
    