spring:
  application:
    name: EXPENSE-SERVICE
  jackson:
    date-format: yyyy-MM-dd
  datasource:
    url: jdbc:postgresql://localhost:5432/Microservice
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8083

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
  service-url:
    defaultZone: http://localhost:8761/eureka
    
   
